apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabari-alpha
  labels:
    app: sabari-alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sabari-alpha
  template:
    metadata:
      labels:
        app: sabari-alpha
    spec:
      containers:
        - name: cont1
          image: 910230630650.dkr.ecr.us-east-1.amazonaws.com/sabari-cicd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "dev"
